server:
  port: 3696
spring:
  datasource:
    url: jdbc:mysql://localhost:7898/SOLID1?createDatabaseIfNotExist=true
    username: root
    password: amin2005
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
    open-in-view: false

